### ISSUE TITLE
Post order is different

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/noddity#1]
Post order in the sidebar does not match the post order on http://noddity.com.

**Comment by ArtskydJ** [comment]
Not sure if this is an issue with `noddity-render-dom` or this module.

**Comment by ArtskydJ** [comment]
[butler.getPosts(...)](https://github.com/TehShrike/noddity-butler#butlergetpostsoptions-cb)

## [previous implementation](https://github.com/TehShrike/noddity/blob/381f0d1bd21b8f9c45011707d0ebdc04a2deafe5/js/mainViewModel.js#L39)
```js
posts.reverse().filter(function(post) {
	return typeof post.metadata.title === 'string'
}).map(function(post) {
	return {
		title: post.metadata.title,
		filename: post.filename
	}
})
```

- Post/template documentation
- The Noddity back end: how posts and stuff work
- The Noddity front end: how caching and stuff works
- Installation
- Services
- The future of Noddity
- Contribute, licensing

## [current implementation](https://github.com/ArtskydJ/noddity-render-dom/blob/master/index.js#L177)
```js
posts.filter(function(post) {
	return post.metadata.date
}).map(function(post) {
	return extend(post, post.metadata)
})
```

- Contribute, licensing
- The future of Noddity
- Services
- Installation
- The Noddity front end: how caching and stuff works
- The Noddity back end: how posts and stuff work
- Post/template documentation

-----

/cc @TehShrike do you have a preference for which way the posts should be ordered? (I think the reverse function was so recent posts would be at the top.)

**Comment by TehShrike** [comment]
ah yeah, it should probably be this:

```js
posts.reverse().filter(function(post) {
    return typeof post.metadata.title === 'string' && post.metadata.date
}).map(function(post) {
    return extend(post, post.metadata)
})

```

**Comment by ArtskydJ** [comment]
Fixed in https://github.com/ArtskydJ/noddity/commit/d1be62a729a9763a7bab6b9d502125da81f7fe11.

**Comment by ArtskydJ** [comment]
The static renderer and the dom renderer sort the postList differently.

https://github.com/TehShrike/noddity-render-static/blob/master/index.js#L175
https://github.com/ArtskydJ/noddity-render-dom/blob/master/index.js#L187

It might make sense to reverse it if you have a blog...

```json
[ "2015-11-24-post.md",
  "2014-10-13-post.md",
  "2013-09-02-post.md" ]
```

...but not so much if you have an information site.

```json
[ "introduction-to-awesome.md",
  "explain-more-of-the-awesome.md",
  "trick-them-into-purchasing-the-awesome.md" ]
```


My personal preference, is to leave the index.json order unchanged in the postList. If they want the postList reversed, they can do so in a template:

```html
{{#postList.reverse()}}
    <a href="#{{filename}}">{{title}}</a><br>
{{/}}
```

/cc @TehShrike

**Comment by ArtskydJ** [comment]
Bump @TehShrike.

The static renderer and dom renderer sort the post list differently...

**Comment by TehShrike** [comment]
Yeah, they should both sort the same way.  That's one issue.

The other issue is: how should they sort?

When I've wanted arbitrary ordering in the sidebar before, I've replaced the mustache loop with a [sidebar.md](https://github.com/TehShrike/noddity/blob/master/js/index.js#L24) template.

Right now the butler [does its own sorting](https://github.com/TehShrike/noddity-butler/blob/master/lib/index_manager.js#L57).  In theory, its ordering should be "correct" and neither renderer should be re-sorting.

Except of course that what is "correct" isn't obvious.

Maybe the butler and renderers should do no ordering or filtering at all, but instead the renderers could expose a `sortByDate` function to the renderers that the default templates could use to replicate the current blog-optimized sorting (with any desired filtering done in the template as well).

It would be a breaking change, but probably not an incredibly onerous one (not as annoying as inconsistent ordering between the static and dynamic versions of your site, anyway).

**Comment by ArtskydJ** [comment]
I agree, I don't think the renderers should order or filter the `postList`.

It looks like the posts are already sorted oldest-date-first in the butler, and a template could probably reverse the posts for blogs, so maybe a `sortByDate` function would be unnecessary?

**Comment by TehShrike** [comment]
I was thinking that we remove ordering from the Butler code too, and leave it all to the templates.  Otherwise, your index.json ordering is still lost.

**Comment by ArtskydJ** [comment]
True...

Would it be cleanest to expose a sorting function, or another post list, but sorted by date? E.g. `dateSortedPostList`

The upside with a function is that there could be a parameter for ascending/descending. And then they're less likely to incorrectly use `.reverse()` which mutates the array.
