### ISSUE TITLE
RFC: metadata is not exposed anymore

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/noddity#4]
Renamed instances of `{{metadata.title}}` to `{{title}}` since `metadata` isn't in scope. See https://github.com/ArtskydJ/noddity/commit/a2043c96ec34cc87d933593a4271eed733476d44.

@TehShrike Should this backward-compatibility be added? (To the `noddity-render-static` module as well...)

**Comment by TehShrike** [comment]
I think the metadata object of the current post should be available on the scope, yeah.

**Comment by ArtskydJ** [comment]
@TehShrike https://github.com/ArtskydJ/noddity-render-dom/commit/d2ccd18b19a2aa0f63effebb318ece491fe83624 Does that look right?

**Comment by TehShrike** [comment]
Looks good to me!

**Comment by ArtskydJ** [comment]
That was quick! Thanks!
